version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: laravel_task
      DB_USERNAME: laravel_user
      DB_PASSWORD: password123

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: laravel_task
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpass

volumes:
  db-data:
